### ISSUE TITLE
Failed to open a VMM Handle

### ISSUE THREAD

**Issue by Trinox-stack** [Snoogens101/ApexDMA#11]
Erverytime running the compiled version i get the following result:
loading libraries...
Successfully loaded libraries!
-----------------------------
Apex Legends DMA Paste
-----------------------------
inizializing...
[!] Failed to open a VMM Handle
dumping memory map to file...
[!] ERROR: Could not dump memory map!
Defaulting to no memory map!
[!] Initialization failed with Memory map? Try without MMap
[!] Initialization failed! Is the DMA in use or disconnected?
Failed to initilize DMA
Press ENTER to continue...
DMA initilized
Failed to initialize keyboard hotkeys through kernel.
Press ENTER to continue...
-----------------------------
Failed to open config file: config.cfg
Config initialized
-----------------------------

what am i doing wrong? 
dma card is working normally.

**Comment by lishang0808** [comment]
vmm.dll     leechcore.dll   FTD3XX.dll 尝试更新一下
