### ISSUE TITLE
Failed to initialize keyboard hotkeys through kernel.

### ISSUE THREAD

**Issue by AVGGAMER07** [Snoogens101/ApexDMA#6]
Hey man, i keep getting Failed to initialize keyboard hotkeys through kernel, everything works besides that and no aa work because of that error. im on windows 10 build 22h2

**Comment by AVGGAMER07** [comment]
If you can please give me any advice to fix it that would be appropriate

**Comment by Snoogens101** [comment]
Restart your gaming pc

**Comment by AVGGAMER07** [comment]
Hey, I restarted my PC multiple times. I have windows 10 in my game PC. Is that the problem

**Comment by Snoogens101** [comment]
> Hey, I restarted my PC multiple times. I have windows 10 in my game PC. Is that the problem 

Me and three of my friends use Win10 on the gaming pc without any issues, not sure what would be the issue with yours.

**Comment by AVGGAMER07** [comment]
Hey. Me and my brother tested it as well. Both getting the same error I listed above. Not sure. I looked at the code and everything looks fine. Do you have time to add me on discord?

**Comment by AVGGAMER07** [comment]
So I tried your new update and I'm getting the same error. The way I'm compiling is set to release and I didn't change anything else since I'm just trying to get it to work. My kmbox works fine it shows it's connected. Just my input manager isn't getting any feed since it fails

**Comment by Snoogens101** [comment]
No idea mate, it works for my friends so idk what to tell ya. The code is available right here so play around with it.

**Comment by AVGGAMER07** [comment]
Alright. I figured it out. It was because I was changing complie settings for some reason that caused an issue. My second and only issue is that my connection to the kmbox is not working. I put com port 5 in settings. And it's not working for me. Is there any advice

**Comment by Snoogens101** [comment]
No, you're probably changing shit and it's breaking all kinds of stuff. You're on your own.

**Comment by AVGGAMER07** [comment]
Hey. I did not change anything. When I downloaded the zip it was set to debug complie and it wasn't working. So I changed it to release and it worked. I'm not trying to be rude. I just wanted to connect the kmbox. For setting do I have to do com5 or just 5?

**Comment by AVGGAMER07** [comment]
Hey brother. I found the fix for it. I went to the kmbox settings and set_com_port to 5 manually. I'm not sure why it isn't working otherwise. Taking a look and see if I can find the fix for it. Otherwise can you take a look

**Comment by AVGGAMER07** [comment]
Hey brother. I found the fix for it. I went to the kmbox settings and set_com_port to 5 manually. I'm not sure why it isn't working otherwise. Taking a look and see if I can find the fix for it. Otherwise can you take a look

**Comment by Snoogens101** [comment]
> Hey brother. I found the fix for it. I went to the kmbox settings and set_com_port to 5 manually. I'm not sure why it isn't working otherwise. Taking a look and see if I can find the fix for it. Otherwise can you take a look

And if you set it in the config to =5 it doesn't work?

**Comment by AVGGAMER07** [comment]
No, so i set it to =5 in config.cfg and i set it manually to 5 in aimbot.hpp int KmboxComPort = 5; and it still shows me failed. Now i start the program it says my KM fails to initialize but since i set_com_port manually it still is connecting. Is it working for you?

**Comment by AVGGAMER07** [comment]
if (comPort.open(5, 115200)) 
            {
                std::cout << "Kmbox B+ Pro initialized successfully." << std::endl;         
            }
            else {
                std::cout << "Kmbox B+ Pro failed to initialize." << std::endl;
            }

        }
    }
    
    So it was because of that, i set an invalid com and it says successful lol...

**Comment by AVGGAMER07** [comment]
Hey i have a question, 

 if (!mem.GetKeyboard()->IsKeyDown(VK_RBUTTON) && !Myself->IsInAttack) { ReleaseTarget(); return; } <- 
 
  this is for manual aimassist,
  
  (RelativePosition.y / ((Myself->IsInAttack || mem.GetKeyboard()->IsKeyDown(VK_LBUTTON)) ? dynamicSmoothing * RecoilCompensation : dynamicSmoothing))
  
   im assuming this is to calculate everything

my question even if i don't use my aim key and just left click to shoot it does AIM ASSIST, 
 i thought i'd use aim assist key to actually AA, i can't find anywhere else where it says mem.GetKeyboard()->IsKeyDown(VK_LBUTTON) to aa

**Comment by Snoogens101** [comment]
`if (!mem.GetKeyboard()->IsKeyDown(VK_RBUTTON) && !Myself->IsInAttack) { ReleaseTarget(); return; }`

"If not holding down right click and not shooting, then release target"
Which equals:
if holding down right click - dont release, proceed with aimbot.
if shooting - dont release, proceed with aimbot.

what button is shooting? left click. :)

**Comment by AVGGAMER07** [comment]
Hey i know what that means brother, i mean if i dont use this if (!mem.GetKeyboard()->IsKeyDown(VK_RBUTTON) && !Myself->IsInAttack) { ReleaseTarget(); return; }

,if i dont hold right click, and i do normal left click shooting its still AAing

**Comment by Snoogens101** [comment]
> Hey i know what that means brother, i mean if i dont use this if (!mem.GetKeyboard()->IsKeyDown(VK_RBUTTON) && !Myself->IsInAttack) { ReleaseTarget(); return; }
> 
> 
> 
> ,if i dont hold right click, and i do normal left click shooting its still AAing

You are legit retarded - you don't understand. Read up on basic programming and try again later.
